### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jackmaney** [sscotth/file-icon-supplement#9]
Generated by Atom's [Deprecation Cop](https://github.com/atom/deprecation-cop):

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> ```
> Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
> FileIconSupplementView.addTabClass (/Users/jackmaney/.atom/packages/file-icon-supplement/lib/file-> icon-supplement-view.coffee:89:18)
> ```

**Comment by sscotth** [comment]
Resolved in 6362f7a20ec4c240d7a6a0068f0f006bcbca54fd
